# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: notebook
# email: you can put an email address here
description: > # this means to ignore newlines until "baseurl:"
  a place to jot things down.
baseurl: "" # the subpath of your site, e.g. /blog /notebook
url: "http://dmcwo.github.io/notebook" # the base hostname & protocol for your site
paginate: 5
twitter_username: dmcwo
github_username:  dmcwo
linkedin_username: doug-worsham

# gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
